# Regenerates Config/CookExcludeDeveloperContent.ini used by packaging.
# Lists directories that should never cook into Shipping builds.

[CmdletBinding()]
param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"

$ConfigDir = Join-Path $RepoRoot "Config"
$OutFile = Join-Path $ConfigDir "CookExcludeDeveloperContent.ini"

$ExcludeDirs = @(
    "Content/Python",
    "Content/Developers",
    "Content/Collections",
    "Intermediate",
    "Saved",
    "Tools",
    "DerivedDataCache"
)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("; Auto-generated by Tools/Strip-DeveloperContent.ps1 - do not hand-edit.")
$lines.Add("; Referenced by DefaultGame.ini packaging DirectoriesToNeverCook.")
$lines.Add("")
$lines.Add("[CookExclude]")
$lines.Add("bEnabled=True")

foreach ($dir in $ExcludeDirs) {
    $full = Join-Path $RepoRoot ($dir -replace "/", "\")
    $lines.Add("Directory=$dir")
    if (-not (Test-Path $full)) {
        Write-Host "Note: exclude path not present yet: $dir"
    }
}

$ExcludeMaps = @(
    "/Game/Variant_Combat",
    "/Game/Variant_Platforming",
    "/Game/Variant_SideScrolling"
)

$lines.Add("")
$lines.Add("[CookExclude.Maps]")
foreach ($m in $ExcludeMaps) {
    $lines.Add("Map=$m")
}

Set-Content -Path $OutFile -Value ($lines -join "`r`n") -Encoding UTF8
Write-Host "Wrote $OutFile"
